# tools/report_generator.py

import os
import re
import sys
from fpdf import FPDF

def latin1_safe(text: str) -> str:
    """
    Converts special unicode characters (like long dashes or ligatures)
    into standard Latin-1 strings so FPDF core fonts never fail.
    """
    if not text:
        return ""
    replacements = {
        "\u2014": "-",   # em-dash
        "\u2013": "-",   # en-dash
        "\u2018": "'",   # open single quote
        "\u2019": "'",   # close single quote
        "\u201c": '"',   # open double quote
        "\u201d": '"',   # close double quote
        "œ": "oe",       # oe ligature
        "Œ": "Oe",
        "æ": "ae",
        "Æ": "Ae",
        "…": "...",
        "µ": "u",
    }
    t = str(text)
    for k, v in replacements.items():
        t = t.replace(k, v)
    return t.encode("latin-1", errors="replace").decode("latin-1")

class MedicalReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, latin1_safe("MEDAGENT - DOSSIER CLINIQUE DE SYNTHESE"), border=0, ln=1, align="L")
        self.set_draw_color(220, 220, 220)
        self.line(10, 16, 200, 16)
        self.ln(5)
        
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, latin1_safe(f"Page {self.page_no()}/{{nb}} - Genere par MedAgent Pipeline - Document confidentiel"), align="C")


def clean_markdown_for_pdf(text: str) -> str:
    """Removes basic markdown formatting like asterisks or hashtags for clean PDF rendering."""
    cleaned = re.sub(r"\*\*|__", "", text)
    cleaned = re.sub(r"###?\s+", "", cleaned)
    # Convert bullet points
    cleaned = re.sub(r"-\s+", "• ", cleaned)
    # Remove HTML-like alerts
    cleaned = re.sub(r"\[!.*?\]", "", cleaned)
    return cleaned.strip()


def generate_reports(patient_info: dict, annotated_params: list, alert_report: dict, summary_text: str, output_path_base: str):
    """
    Generates Markdown, HTML and PDF formats of the medical analysis report.
    
    Args:
        patient_info: dict with keys: age, gender, reason, history
        annotated_params: list of dicts with parameter, value, unit, status, normal_range, clinical_risk
        alert_report: dict with critical_count, abnormal_count, alerts list
        summary_text: the text summary generated by the writer agent
        output_path_base: absolute path without extension, e.g. "output/summaries/report_01_summary"
    """
    os.makedirs(os.path.dirname(output_path_base), exist_ok=True)
    
    # ── 1. GENERATE MARKDOWN REPORT ──
    markdown_path = output_path_base + ".md"
    with open(markdown_path, "w", encoding="utf-8") as f:
        f.write(f"# RAPPORT CLINIQUE MEDAGENT — SYNTHÈSE BIOLOGIQUE\n\n")
        f.write(f"## INFORMATIONS PATIENT\n")
        f.write(f"- **Genre** : {patient_info.get('gender', 'N/A')}\n")
        f.write(f"- **Âge** : {patient_info.get('age', 'N/A')}\n")
        f.write(f"- **Motif de consultation** : {patient_info.get('reason', 'Non précisé')}\n")
        f.write(f"- **Antécédents** : {patient_info.get('history', 'Non précisé')}\n\n")
        
        f.write(f"## STATISTIQUES DES ALERTES\n")
        f.write(f"- 🔴 **Alertes critiques** : {alert_report.get('critical_count', 0)}\n")
        f.write(f"- 🟡 **Paramètres anormaux** : {alert_report.get('abnormal_count', 0)}\n\n")
        
        f.write(f"## RÉSULTATS D'ANALYSES DÉTAILLÉS\n")
        f.write(f"| Paramètre | Valeur | Unité | Valeurs de Référence | Statut | Risque Clinique |\n")
        f.write(f"| :--- | :---: | :---: | :---: | :---: | :--- |\n")
        for p in annotated_params:
            status_icon = "🔴 CRITIQUE" if p['status'] == "CRITICAL" else \
                          "🟡 ANORMAL" if p['status'] == "ABNORMAL" else "🟢 NORMAL"
            f.write(f"| {p['parameter']} | {p['value']} | {p['unit']} | {p['normal_range']} | {status_icon} | {p.get('clinical_risk') or 'Normal'} |\n")
        f.write("\n")
        
        f.write(f"## SYNTHÈSE CLINIQUE & RECOMMANDATIONS D'URGENCE\n")
        f.write(f"{summary_text}\n")

    # ── 2. GENERATE HTML REPORT (Visual Excellence) ──
    html_path = output_path_base + ".html"
    
    # CSS Classes for Badges
    param_rows_html = ""
    for p in annotated_params:
        status_cls = "badge-critical" if p['status'] == "CRITICAL" else \
                     "badge-abnormal" if p['status'] == "ABNORMAL" else "badge-normal"
        status_lbl = "CRITIQUE" if p['status'] == "CRITICAL" else \
                     "ANORMAL" if p['status'] == "ABNORMAL" else "NORMAL"
        risk_text = p.get('clinical_risk') or 'Aucun risque identifié'
        
        param_rows_html += f"""
        <tr>
            <td style="font-weight: 600;">{p['parameter']}</td>
            <td style="text-align: center; font-family: monospace; font-size: 1.1rem; font-weight: 700;">{p['value']}</td>
            <td style="text-align: center; color: #666;">{p['unit']}</td>
            <td style="text-align: center; font-family: monospace;">{p['normal_range']}</td>
            <td style="text-align: center;"><span class="badge {status_cls}">{status_lbl}</span></td>
            <td style="font-size: 0.9rem; color: #444;">{risk_text}</td>
        </tr>
        """
        
    summary_formatted_html = summary_text.replace("\n", "<br>")
    
    html_content = f"""<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rapport Médical MedAgent</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&family=Plus+Jakarta+Sans:wght@400;600;800&display=swap" rel="stylesheet">
    <style>
        :root {{
            --bg-color: #f8fafc;
            --primary: #0f172a;
            --normal: #0ea5e9;
            --normal-light: #e0f2fe;
            --abnormal: #f59e0b;
            --abnormal-light: #fef3c7;
            --critical: #ef4444;
            --critical-light: #fee2e2;
            --card-bg: #ffffff;
            --text: #1e293b;
        }}
        body {{
            font-family: 'Plus Jakarta Sans', 'Outfit', sans-serif;
            background-color: var(--bg-color);
            color: var(--text);
            margin: 0;
            padding: 30px 15px;
            line-height: 1.6;
        }}
        .container {{
            max-width: 1000px;
            margin: 0 auto;
        }}
        header {{
            background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
            color: white;
            padding: 40px;
            border-radius: 24px;
            box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08);
            margin-bottom: 30px;
            position: relative;
            overflow: hidden;
        }}
        header::after {{
            content: '';
            position: absolute;
            top: -50%;
            right: -20%;
            width: 300px;
            height: 300px;
            background: rgba(14, 165, 233, 0.15);
            border-radius: 50%;
            filter: blur(50px);
        }}
        .header-title {{
            margin: 0;
            font-size: 2.2rem;
            font-weight: 800;
            letter-spacing: -0.5px;
        }}
        .header-subtitle {{
            margin: 5px 0 0 0;
            color: #94a3b8;
            font-weight: 400;
        }}
        .grid-2 {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 30px;
            margin-bottom: 30px;
        }}
        @media(max-width: 768px) {{
            .grid-2 {{ grid-template-columns: 1fr; }}
        }}
        .card {{
            background-color: var(--card-bg);
            border-radius: 20px;
            padding: 30px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.02);
            border: 1px solid #e2e8f0;
        }}
        .card-title {{
            font-size: 1.25rem;
            font-weight: 700;
            margin-top: 0;
            margin-bottom: 20px;
            color: var(--primary);
            border-bottom: 2px solid #f1f5f9;
            padding-bottom: 10px;
            display: flex;
            align-items: center;
            gap: 10px;
        }}
        .patient-info-list {{
            list-style: none;
            padding: 0;
            margin: 0;
        }}
        .patient-info-list li {{
            display: flex;
            justify-content: space-between;
            padding: 10px 0;
            border-bottom: 1px solid #f8fafc;
        }}
        .patient-info-list li span.label {{
            font-weight: 600;
            color: #64748b;
        }}
        .patient-info-list li span.value {{
            font-weight: 700;
            color: #0f172a;
        }}
        .stats-container {{
            display: flex;
            gap: 20px;
            justify-content: space-around;
            height: 80%;
            align-items: center;
        }}
        .stat-box {{
            text-align: center;
            padding: 15px;
            border-radius: 16px;
            width: 40%;
        }}
        .stat-box.critical {{
            background-color: var(--critical-light);
            color: var(--critical);
        }}
        .stat-box.abnormal {{
            background-color: var(--abnormal-light);
            color: var(--abnormal);
        }}
        .stat-num {{
            font-size: 2.5rem;
            font-weight: 800;
            margin: 0;
        }}
        .stat-label {{
            font-size: 0.85rem;
            font-weight: 600;
            margin: 5px 0 0 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }}
        th {{
            background-color: #f8fafc;
            color: #475569;
            font-weight: 700;
            text-align: left;
            padding: 14px 18px;
            border-bottom: 2px solid #e2e8f0;
        }}
        td {{
            padding: 16px 18px;
            border-bottom: 1px solid #f1f5f9;
        }}
        tr:hover {{
            background-color: #f8fafc;
        }}
        .badge {{
            display: inline-block;
            padding: 6px 12px;
            border-radius: 12px;
            font-size: 0.75rem;
            font-weight: 800;
            letter-spacing: 0.5px;
        }}
        .badge-normal {{
            background-color: #e0f2fe;
            color: #0369a1;
        }}
        .badge-abnormal {{
            background-color: var(--abnormal-light);
            color: #b45309;
        }}
        .badge-critical {{
            background-color: var(--critical-light);
            color: #b91c1c;
            animation: pulse 2s infinite;
        }}
        @keyframes pulse {{
            0% {{ opacity: 1; }}
            50% {{ opacity: 0.75; }}
            100% {{ opacity: 1; }}
        }}
        .summary-text {{
            font-size: 1.05rem;
            color: #334155;
            background-color: #f8fafc;
            padding: 25px;
            border-radius: 16px;
            border-left: 5px solid #0f172a;
            white-space: pre-line;
            font-family: inherit;
        }}
        footer {{
            text-align: center;
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            color: #94a3b8;
            font-size: 0.85rem;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1 class="header-title">SYNTHÈSE DE DOSSIER CLINIQUES</h1>
            <p class="header-subtitle">Rapport d'analyse automatisé MedAgent Pipeline</p>
        </header>

        <div class="grid-2">
            <div class="card">
                <h2 class="card-title">👤 Profil & Constantes Patient</h2>
                <ul class="patient-info-list">
                    <li><span class="label">Genre</span><span class="value">{patient_info.get('gender', 'N/A')}</span></li>
                    <li><span class="label">Âge</span><span class="value">{patient_info.get('age', 'N/A')}</span></li>
                    <li><span class="label">Motif Clinique</span><span class="value">{patient_info.get('reason', 'N/A')}</span></li>
                    <li><span class="label">Antécédents</span><span class="value">{patient_info.get('history', 'N/A')}</span></li>
                </ul>
            </div>
            <div class="card">
                <h2 class="card-title">🚨 Gravité & Alertes Actives</h2>
                <div class="stats-container">
                    <div class="stat-box critical">
                        <p class="stat-num">{alert_report.get('critical_count', 0)}</p>
                        <p class="stat-label">ALERTES CRITIQUES</p>
                    </div>
                    <div class="stat-box abnormal">
                        <p class="stat-num">{alert_report.get('abnormal_count', 0)}</p>
                        <p class="stat-label">VALEURS ANORMALES</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card" style="margin-bottom: 30px;">
            <h2 class="card-title">🧪 Résultats des Analyses Biologiques</h2>
            <div style="overflow-x: auto;">
                <table>
                    <thead>
                        <tr>
                            <th>Paramètre</th>
                            <th style="text-align: center;">Valeur</th>
                            <th style="text-align: center;">Unité</th>
                            <th style="text-align: center;">Valeurs de Réf.</th>
                            <th style="text-align: center;">Statut</th>
                            <th>Commentaire Clinique / Risque</th>
                        </tr>
                    </thead>
                    <tbody>
                        {param_rows_html}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card">
            <h2 class="card-title">📝 Conclusions de l'Agent MedAgent</h2>
            <div class="summary-text">
                {summary_formatted_html}
            </div>
        </div>

        <footer>
            Document à caractère médical confidentiel — Généré par MedAgent multi-agent IA le 2026.
        </footer>
    </div>
</body>
</html>
"""
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    # ── 3. GENERATE PDF REPORT (Professional PDF for Doctors) ──
    pdf_path = output_path_base + ".pdf"
    
    pdf = MedicalReportPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Title Banner
    pdf.set_fill_color(240, 244, 248)
    pdf.rect(10, 20, 190, 18, "F")
    pdf.set_y(22)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, latin1_safe("RAPPORT DE SYNTHESE CLINIQUE & BIOLOGIQUE"), align="C", ln=1)
    pdf.ln(4)

    # Patient info box (2 columns)
    pdf.set_fill_color(255, 255, 255)
    pdf.set_draw_color(200, 200, 200)
    pdf.rect(10, 42, 190, 28)
    
    pdf.set_y(44)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(30, 6, latin1_safe("Genre :"), 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(60, 6, latin1_safe(str(patient_info.get('gender', 'N/A'))), 0, 0)
    
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(30, 6, latin1_safe("Motif :"), 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(60, 6, latin1_safe(str(patient_info.get('reason', 'N/A'))), 0, 1)

    pdf.set_x(14)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(30, 6, latin1_safe("Age :"), 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(60, 6, latin1_safe(str(patient_info.get('age', 'N/A'))), 0, 0)

    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(30, 6, latin1_safe("Antecedents :"), 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(60, 6, latin1_safe(str(patient_info.get('history', 'N/A'))), 0, 1)
    
    pdf.set_x(14)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(30, 6, latin1_safe("Etat des Alertes :"), 0, 0)
    pdf.set_font("Helvetica", "B", 9)
    crit_count = alert_report.get('critical_count', 0)
    abn_count = alert_report.get('abnormal_count', 0)
    if crit_count > 0:
        pdf.set_text_color(185, 28, 28) # Red
        alert_summary = f"{crit_count} CRITIQUE(S) "
    else:
        pdf.set_text_color(3, 105, 161) # Blue
        alert_summary = "Aucune alerte critique "
        
    pdf.cell(0, 6, latin1_safe(f"{alert_summary}/ {abn_count} anomalie(s)"), 0, 1)
    pdf.set_text_color(15, 23, 42) # reset text color
    pdf.ln(6)

    # ── Draw Parameters Table ──
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 8, latin1_safe("Analyses biologiques detaillees"), ln=1)
    
    # Table Header
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.cell(45, 7, latin1_safe("Parametre"), 1, 0, "L", True)
    pdf.cell(20, 7, latin1_safe("Valeur"), 1, 0, "C", True)
    pdf.cell(15, 7, latin1_safe("Unite"), 1, 0, "C", True)
    pdf.cell(25, 7, latin1_safe("Normes"), 1, 0, "C", True)
    pdf.cell(22, 7, latin1_safe("Statut"), 1, 0, "C", True)
    pdf.cell(63, 7, latin1_safe("Risque Clinique"), 1, 1, "L", True)
    
    # Table Rows
    pdf.set_font("Helvetica", "", 8)
    for p in annotated_params:
        # Save positions for wrapping
        x = pdf.get_x()
        y = pdf.get_y()
        
        pdf.cell(45, 6, latin1_safe(str(p['parameter'])), 1, 0, "L")
        
        # bold value
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.cell(20, 6, latin1_safe(str(p['value'])), 1, 0, "C")
        pdf.set_font("Helvetica", "", 8)
        
        pdf.cell(15, 6, latin1_safe(str(p['unit'])), 1, 0, "C")
        pdf.cell(25, 6, latin1_safe(str(p['normal_range'])), 1, 0, "C")
        
        # Color status
        if p['status'] == "CRITICAL":
            pdf.set_text_color(185, 28, 28)
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(22, 6, latin1_safe("CRITIQUE"), 1, 0, "C")
            pdf.set_text_color(15, 23, 42)
            pdf.set_font("Helvetica", "", 8)
        elif p['status'] == "ABNORMAL":
            pdf.set_text_color(180, 83, 9)
            pdf.cell(22, 6, latin1_safe("ANORMAL"), 1, 0, "C")
            pdf.set_text_color(15, 23, 42)
        else:
            pdf.set_text_color(3, 105, 161)
            pdf.cell(22, 6, latin1_safe("NORMAL"), 1, 0, "C")
            pdf.set_text_color(15, 23, 42)
            
        # Clinical Risk with multi-line support
        risk_text = p.get('clinical_risk') or 'Normal'
        # Draw a cell with small text and border
        pdf.cell(63, 6, latin1_safe(risk_text[:38] + ('...' if len(risk_text) > 38 else '')), 1, 1, "L")
        
    pdf.ln(8)
    
    # ── Summary & Recommendations ──
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 8, latin1_safe("Synthese Clinique & Actions suggerees"), ln=1)
    
    pdf.set_font("Helvetica", "", 9)
    cleaned_summary = clean_markdown_for_pdf(summary_text)
    
    # Border for the summary box
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(15, 23, 42)
    
    pdf.multi_cell(0, 5.5, latin1_safe(cleaned_summary), border="L", fill=True)
    
    # Save the PDF
    pdf.output(pdf_path)

